services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/code/entrypoint.sh"]
    env_file:
      - .env
    ports:
      - 3859:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/code/src
      - .env:/code/.env
      - ./logs:/code/logs
      - ./migrations:/code/migrations
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=ERROR
    networks:
      - web

  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 2s
      timeout: 5s
      retries: 10
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=ERROR
    networks:
      - web

  pgadmin:
   container_name: pgadmin4
   image: dpage/pgadmin4:latest
   restart: always
   ports:
     - 5050:80
   volumes:
     - pgadmin-data:/var/lib/pgadmin
   env_file:
     - .env
   depends_on:
     db:
       condition: service_healthy
     web:
       condition: service_started
   attach: false
   environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=ERROR
   networks:
      - web


  parser:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started
    command: [ "python", "-u", "-m", "src.parser.parser" ]
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=ERROR
    volumes:
      - ./src:/code/src
      - ./logs:/code/logs
    networks:
      - web


  initial_script:
     build:
       context: .
       dockerfile: Dockerfile
     env_file:
       - .env
     depends_on:
       db:
         condition: service_healthy
       web:
         condition: service_started
     command: python -m src.scripts.init_script
     volumes:
       - ./src:/code/src
     environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=ERROR
     networks:
      - web

volumes:
  postgres-data:
  pgadmin-data:

networks:
  web:
    external: true
