# Exported from Render on 2025-01-20T15:21:27Z

previews:
  generation: automatic

databases:
- name: postgres-wagers
  databaseName: postgres_wagers
  user: postgres_wagers_user
  plan: basic-1gb
  region: frankfurt
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
  diskSizeGB: 1

services:
- type: web
  name: wagers-dev
  runtime: docker
  repo: https://github.com/Loopeq/wagers-dev
  plan: starter
  envVars:
  - key: .env
    sync: false
  region: frankfurt
  dockerContext: .
  autoDeploy: false
  dockerfilePath: ./Dockerfile
  domains:
  - api.swaeger.com

- type: worker
  name: parser-worker
  runtime: python
  repo: https://github.com/Loopeq/wagers-dev
  plan: starter
  envVars:
  - key: .env
    sync: false
  region: frankfurt
  autoDeploy: false
  startCommand: "python -m src.parser.parser"

- type: worker
  name: db-init-worker
  runtime: python
  repo: https://github.com/Loopeq/wagers-dev
  plan: starter
  envVars:
  - key: .env
    sync: false
  region: frankfurt
  autoDeploy: false
  startCommand: "python -m src.scripts.init_script"
version: "1"
