"""rework logic

Revision ID: 1ec65a66964a
Revises: 0a399668a9ab
Create Date: 2024-09-16 14:41:19.708373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec65a66964a'
down_revision: Union[str, None] = '0a399668a9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

betvaluetypeenum = sa.Enum('home', 'away', 'over', 'under',  name='betvaluetypesenum')


def upgrade() -> None:
    betvaluetypeenum.create(op.get_bind())

    op.add_column('bet_value', sa.Column('type', betvaluetypeenum, nullable=False))



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet_value', 'type')

    # ### end Alembic commands ###
