"""empty message

Revision ID: 348013c084dd
Revises: 34cfcc26644a
Create Date: 2024-09-14 15:10:35.297281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '348013c084dd'
down_revision: Union[str, None] = '34cfcc26644a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_member', 'status',
               existing_type=postgresql.ENUM('win', 'lose', 'over', 'under', name='matchresultenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_member', 'status',
               existing_type=postgresql.ENUM('win', 'lose', 'over', 'under', name='matchresultenum'),
               nullable=False)
    # ### end Alembic commands ###
