"""empty message

Revision ID: 5f5c2ef6691e
Revises: 55c1923622f3
Create Date: 2024-09-14 16:34:23.798442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5c2ef6691e'
down_revision: Union[str, None] = '55c1923622f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_match_member_combination', 'bet', ['match_member_id', 'type', 'period'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_match_member_combination', 'bet', type_='unique')
    # ### end Alembic commands ###
