"""add bet change model

Revision ID: a6b4c77e432f
Revises: a4ef98900531
Create Date: 2024-09-26 16:40:24.536825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b4c77e432f'
down_revision: Union[str, None] = 'a4ef98900531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_change',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('old_bet_id', sa.Integer(), nullable=False),
    sa.Column('new_bet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['new_bet_id'], ['bet.id'], ),
    sa.ForeignKeyConstraint(['old_bet_id'], ['bet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet_change')
    # ### end Alembic commands ###
