"""empty message

Revision ID: b95e9cfea20f
Revises: 5f5c2ef6691e
Create Date: 2024-09-14 16:52:42.601378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95e9cfea20f'
down_revision: Union[str, None] = '5f5c2ef6691e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_match_combination', 'match_member', ['match_id', 'side'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_match_combination', 'match_member', type_='unique')
    # ### end Alembic commands ###
