"""empty message

Revision ID: db8d9dea3223
Revises: 348013c084dd
Create Date: 2024-09-14 15:20:58.382683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8d9dea3223'
down_revision: Union[str, None] = '348013c084dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('match', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('sport', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sport', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('sport_id_seq'::regclass)"),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('match', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('match_id_seq'::regclass)"),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('league', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('league_id_seq'::regclass)"),
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###
