"""remove foreign key to bet change

Revision ID: f1574700983f
Revises: d0247f1264c8
Create Date: 2024-09-27 14:08:27.733680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1574700983f'
down_revision: Union[str, None] = 'd0247f1264c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bet_change_bet_id_fkey', 'bet_change', type_='foreignkey')
    op.drop_column('bet_change', 'bet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_change', sa.Column('bet_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('bet_change_bet_id_fkey', 'bet_change', 'bet', ['bet_id'], ['id'])
    # ### end Alembic commands ###
