"""Archive tables

Revision ID: 00ed2a2acacc
Revises: a346ef47540f
Create Date: 2026-03-04 17:29:11.670995

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00ed2a2acacc"
down_revision: Union[str, None] = "a346ef47540f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bet_archive",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("point", sa.Float(), nullable=True),
        sa.Column("limit", sa.Integer(), nullable=False),
        sa.Column("home_cf", sa.Float(), nullable=False),
        sa.Column("draw_cf", sa.Float(), nullable=True),
        sa.Column("away_cf", sa.Float(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("period", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_bet_archive_latest_version",
        "bet_archive",
        ["match_id", "type", "period", "version"],
        unique=False,
        postgresql_ops={"version": "desc"},
    )
    op.create_index(
        op.f("ix_bet_archive_created_at"), "bet_archive", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_bet_archive_match_id"), "bet_archive", ["match_id"], unique=False
    )
    op.create_table(
        "match_archive",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["league.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["match.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_match_archive_parent_id"), "match_archive", ["parent_id"], unique=False
    )
    op.create_index(
        op.f("ix_match_archive_start_time"),
        "match_archive",
        ["start_time"],
        unique=False,
    )
    op.create_table(
        "match_member_archive",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("home_id", sa.Integer(), nullable=False),
        sa.Column("away_id", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["away_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["home_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "match_id", "home_id", "away_id", name="uq_match_member_archive_combination"
        ),
    )
    op.create_index(
        op.f("ix_match_member_archive_away_id"),
        "match_member_archive",
        ["away_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_member_archive_home_id"),
        "match_member_archive",
        ["home_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_member_archive_match_id"),
        "match_member_archive",
        ["match_id"],
        unique=False,
    )
    op.create_table(
        "match_result_archive",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("team_1_score", sa.Integer(), nullable=False),
        sa.Column("team_2_score", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "match_id", "period", name="uq_match_result_archive_combination"
        ),
    )
    op.create_index(
        op.f("ix_match_result_archive_description"),
        "match_result_archive",
        ["description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_result_archive_match_id"),
        "match_result_archive",
        ["match_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_result_archive_period"),
        "match_result_archive",
        ["period"],
        unique=False,
    )
    op.drop_index(op.f("idx_bet_latest_version"), table_name="bet")
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", "version"],
        unique=False,
        postgresql_ops={"version": "desc"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_bet_latest_version", table_name="bet", postgresql_ops={"version": "desc"}
    )
    op.create_index(
        op.f("idx_bet_latest_version"),
        "bet",
        ["match_id", "type", "period", sa.literal_column("version DESC")],
        unique=False,
    )
    op.drop_index(
        op.f("ix_match_result_archive_period"), table_name="match_result_archive"
    )
    op.drop_index(
        op.f("ix_match_result_archive_match_id"), table_name="match_result_archive"
    )
    op.drop_index(
        op.f("ix_match_result_archive_description"), table_name="match_result_archive"
    )
    op.drop_table("match_result_archive")
    op.drop_index(
        op.f("ix_match_member_archive_match_id"), table_name="match_member_archive"
    )
    op.drop_index(
        op.f("ix_match_member_archive_home_id"), table_name="match_member_archive"
    )
    op.drop_index(
        op.f("ix_match_member_archive_away_id"), table_name="match_member_archive"
    )
    op.drop_table("match_member_archive")
    op.drop_index(op.f("ix_match_archive_start_time"), table_name="match_archive")
    op.drop_index(op.f("ix_match_archive_parent_id"), table_name="match_archive")
    op.drop_table("match_archive")
    op.drop_index(op.f("ix_bet_archive_match_id"), table_name="bet_archive")
    op.drop_index(op.f("ix_bet_archive_created_at"), table_name="bet_archive")
    op.drop_index(
        "idx_bet_archive_latest_version",
        table_name="bet_archive",
        postgresql_ops={"version": "desc"},
    )
    op.drop_table("bet_archive")
    # ### end Alembic commands ###
