"""update user model

Revision ID: 23c4f2cc31d7
Revises: e039af18e7cb
Create Date: 2024-12-24 18:02:52.529653

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23c4f2cc31d7"
down_revision: Union[str, None] = "e039af18e7cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("new_id", sa.Integer(), nullable=False, autoincrement=True)
    )
    op.drop_column("user", "id")
    op.alter_column("user", "new_id", new_column_name="id")
    op.add_column("user", sa.Column("uuid", sa.Uuid(), nullable=False))
    op.add_column("user", sa.Column("disabled", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("superuser", sa.Boolean(), nullable=False))
    op.drop_index("ix_user_email", table_name="user")
    op.create_unique_constraint(None, "user", ["uuid"])
    op.drop_column("user", "is_verified")
    op.drop_column("user", "is_active")
    op.drop_column("user", "hashed_password")
    op.drop_column("user", "is_superuser")
    op.drop_column("user", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("email", sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user",
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user",
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=1024),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user",
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "user", type_="unique")
    op.create_index("ix_user_email", "user", ["email"], unique=True)
    op.alter_column(
        "user",
        "id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("user", "superuser")
    op.drop_column("user", "disabled")
    op.drop_column("user", "uuid")
    # ### end Alembic commands ###
