"""remove bet change table

Revision ID: 270511669ddf
Revises: 56d98ba845b5
Create Date: 2025-01-22 20:03:42.303777

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "270511669ddf"
down_revision: Union[str, None] = "56d98ba845b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bet_change_new_bet_id", table_name="bet_change")
    op.drop_index("ix_bet_change_old_bet_id", table_name="bet_change")
    op.drop_table("bet_change")
    op.alter_column(
        "user",
        "disabled",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "superuser",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "superuser",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "disabled",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.create_table(
        "bet_change",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("old_bet_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("new_bet_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["new_bet_id"],
            ["bet.id"],
            name="bet_change_new_bet_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["old_bet_id"],
            ["bet.id"],
            name="bet_change_old_bet_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="bet_change_pkey"),
    )
    op.create_index(
        "ix_bet_change_old_bet_id", "bet_change", ["old_bet_id"], unique=False
    )
    op.create_index(
        "ix_bet_change_new_bet_id", "bet_change", ["new_bet_id"], unique=False
    )
    # ### end Alembic commands ###
