"""Add indexes

Revision ID: 2ab971cd3294
Revises: fcd67ad87501
Create Date: 2024-10-29 21:08:47.568133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab971cd3294'
down_revision: Union[str, None] = 'fcd67ad87501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bet_created_at'), 'bet', ['created_at'], unique=False)
    op.create_index(op.f('ix_bet_match_id'), 'bet', ['match_id'], unique=False)
    op.create_index(op.f('ix_bet_change_new_bet_id'), 'bet_change', ['new_bet_id'], unique=False)
    op.create_index(op.f('ix_bet_change_old_bet_id'), 'bet_change', ['old_bet_id'], unique=False)
    op.create_index(op.f('ix_match_start_time'), 'match', ['start_time'], unique=False)
    op.create_index(op.f('ix_match_member_match_id'), 'match_member', ['match_id'], unique=False)
    op.create_index('ix_match_member_match_id_side', 'match_member', ['match_id', 'side'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_member_match_id_side', table_name='match_member')
    op.drop_index(op.f('ix_match_member_match_id'), table_name='match_member')
    op.drop_index(op.f('ix_match_start_time'), table_name='match')
    op.drop_index(op.f('ix_bet_change_old_bet_id'), table_name='bet_change')
    op.drop_index(op.f('ix_bet_change_new_bet_id'), table_name='bet_change')
    op.drop_index(op.f('ix_bet_match_id'), table_name='bet')
    op.drop_index(op.f('ix_bet_created_at'), table_name='bet')
    # ### end Alembic commands ###
