"""add user password field

Revision ID: 2d1454eacd3d
Revises: 23c4f2cc31d7
Create Date: 2024-12-24 22:19:59.451089

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d1454eacd3d"
down_revision: Union[str, None] = "23c4f2cc31d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    # ### end Alembic commands ###
