"""bet type remove enum

Revision ID: 4bbf805a1b1e
Revises: 1f8e329f543d
Create Date: 2025-05-20 20:01:11.315932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4bbf805a1b1e"
down_revision: Union[str, None] = "1f8e329f543d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bet",
        "type",
        existing_type=postgresql.ENUM(
            "total", "spread", "team_total", "moneyline", name="bettypeenum"
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_index("idx_bet_latest_version", table_name="bet")
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", "version"],
        unique=False,
        postgresql_ops={"version": "desc"},
    )
    op.create_index(
        op.f("ix_match_result_description"),
        "match_result",
        ["description"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_result_description"), table_name="match_result")
    op.drop_index(
        "idx_bet_latest_version", table_name="bet", postgresql_ops={"version": "desc"}
    )
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", sa.text("version DESC")],
        unique=False,
    )
    op.alter_column(
        "bet",
        "type",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "total", "spread", "team_total", "moneyline", name="bettypeenum"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
