"""user session id

Revision ID: 54e4f51abfc2
Revises: f175fa9536e8
Create Date: 2025-08-17 00:19:26.943688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e4f51abfc2'
down_revision: Union[str, None] = 'f175fa9536e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_bet_latest_version'), table_name='bet')
    op.create_index('idx_bet_latest_version', 'bet', ['match_id', 'type', 'period', 'version'], unique=False, postgresql_ops={'version': 'desc'})
    op.add_column('user', sa.Column('session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'session_id')
    op.drop_index('idx_bet_latest_version', table_name='bet', postgresql_ops={'version': 'desc'})
    op.create_index(op.f('idx_bet_latest_version'), 'bet', ['match_id', 'type', 'period', sa.literal_column('version DESC')], unique=False)
    # ### end Alembic commands ###
