"""user table remove id field

Revision ID: 56d98ba845b5
Revises: 2d1454eacd3d
Create Date: 2024-12-24 22:24:59.894461

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56d98ba845b5"
down_revision: Union[str, None] = "2d1454eacd3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
