"""user created at

Revision ID: 79daa0cfc8b5
Revises: e8a27cfd106b
Create Date: 2025-08-17 19:52:35.782268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79daa0cfc8b5'
down_revision: Union[str, None] = 'e8a27cfd106b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_bet_latest_version'), table_name='bet')
    op.create_index('idx_bet_latest_version', 'bet', ['match_id', 'type', 'period', 'version'], unique=False, postgresql_ops={'version': 'desc'})
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_index('idx_bet_latest_version', table_name='bet', postgresql_ops={'version': 'desc'})
    op.create_index(op.f('idx_bet_latest_version'), 'bet', ['match_id', 'type', 'period', sa.literal_column('version DESC')], unique=False)
    # ### end Alembic commands ###
