"""bet desc index

Revision ID: 89c343baf15c
Revises: d7b33ec194ad
Create Date: 2025-03-01 22:32:42.600324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c343baf15c'
down_revision: Union[str, None] = 'd7b33ec194ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_bet_latest_version', 'bet', ['match_id', 'type', 'period', 'version'], unique=False, postgresql_ops={'version': 'desc'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bet_latest_version', table_name='bet', postgresql_ops={'version': 'desc'})
    # ### end Alembic commands ###
