"""invite code is used

Revision ID: 8ae4942f68b3
Revises: 54e4f51abfc2
Create Date: 2025-08-17 15:01:20.268117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8ae4942f68b3"
down_revision: Union[str, None] = "54e4f51abfc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_bet_latest_version"), table_name="bet")
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", "version"],
        unique=False,
        postgresql_ops={"version": "desc"},
    )
    op.add_column("invite_code", sa.Column("is_used", sa.Boolean(), nullable=False))
    op.alter_column(
        "invite_code",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("TIMEZONE('utc', now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "invite_code",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("TIMEZONE('utc', now())"),
        nullable=False,
    )
    op.drop_index(op.f("ix_invite_code_created_at"), table_name="invite_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_invite_code_created_at"), "invite_code", ["created_at"], unique=False
    )
    op.alter_column(
        "invite_code",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        nullable=True,
    )
    op.alter_column(
        "invite_code",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_column("invite_code", "is_used")
    op.drop_index(
        "idx_bet_latest_version", table_name="bet", postgresql_ops={"version": "desc"}
    )
    op.create_index(
        op.f("idx_bet_latest_version"),
        "bet",
        ["match_id", "type", "period", sa.literal_column("version DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
