"""Bet draw cf

Revision ID: a346ef47540f
Revises: b6c25e460066
Create Date: 2026-03-03 17:41:30.098558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a346ef47540f"
down_revision: Union[str, None] = "b6c25e460066"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bet", sa.Column("draw_cf", sa.DOUBLE_PRECISION(precision=53), nullable=True)
    )

    op.drop_index(op.f("idx_bet_latest_version"), table_name="bet")
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", "version"],
        unique=False,
        postgresql_ops={"version": "desc"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bet",
        "home_cf",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )

    op.drop_index(
        "idx_bet_latest_version", table_name="bet", postgresql_ops={"version": "desc"}
    )
    op.create_index(
        op.f("idx_bet_latest_version"),
        "bet",
        ["match_id", "type", "period", sa.literal_column("version DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
