"""user telegram id

Revision ID: b6c25e460066
Revises: 79daa0cfc8b5
Create Date: 2025-08-23 19:42:34.597307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c25e460066'
down_revision: Union[str, None] = '79daa0cfc8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_bet_latest_version'), table_name='bet')
    op.create_index('idx_bet_latest_version', 'bet', ['match_id', 'type', 'period', 'version'], unique=False, postgresql_ops={'version': 'desc'})
    op.add_column('user', sa.Column('telegram_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telegram_id')
    op.drop_index('idx_bet_latest_version', table_name='bet', postgresql_ops={'version': 'desc'})
    op.create_index(op.f('idx_bet_latest_version'), 'bet', ['match_id', 'type', 'period', sa.literal_column('version DESC')], unique=False)
    # ### end Alembic commands ###
