"""Archives foreign keys

Revision ID: c6bc4282d563
Revises: 00ed2a2acacc
Create Date: 2026-03-04 18:49:23.027452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6bc4282d563"
down_revision: Union[str, None] = "00ed2a2acacc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_bet_latest_version"), table_name="bet")
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", "version"],
        unique=False,
        postgresql_ops={"version": "desc"},
    )
    op.drop_index(op.f("idx_bet_archive_latest_version"), table_name="bet_archive")
    op.create_index(
        "idx_bet_archive_latest_version",
        "bet_archive",
        ["match_id", "type", "period", "version"],
        unique=False,
        postgresql_ops={"version": "desc"},
    )
    op.drop_constraint(
        op.f("bet_archive_match_id_fkey"), "bet_archive", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "bet_archive", "match_archive", ["match_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("match_archive_parent_id_fkey"), "match_archive", type_="foreignkey"
    )
    op.create_foreign_key(None, "match_archive", "match_archive", ["parent_id"], ["id"])
    op.drop_constraint(
        op.f("match_member_archive_match_id_fkey"),
        "match_member_archive",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "match_member_archive",
        "match_archive",
        ["match_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("match_result_archive_match_id_fkey"),
        "match_result_archive",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "match_result_archive",
        "match_archive",
        ["match_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "match_result_archive", type_="foreignkey")
    op.create_foreign_key(
        op.f("match_result_archive_match_id_fkey"),
        "match_result_archive",
        "match",
        ["match_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "match_member_archive", type_="foreignkey")
    op.create_foreign_key(
        op.f("match_member_archive_match_id_fkey"),
        "match_member_archive",
        "match",
        ["match_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "match_archive", type_="foreignkey")
    op.create_foreign_key(
        op.f("match_archive_parent_id_fkey"),
        "match_archive",
        "match",
        ["parent_id"],
        ["id"],
    )
    op.drop_constraint(None, "bet_archive", type_="foreignkey")
    op.create_foreign_key(
        op.f("bet_archive_match_id_fkey"),
        "bet_archive",
        "match",
        ["match_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        "idx_bet_archive_latest_version",
        table_name="bet_archive",
        postgresql_ops={"version": "desc"},
    )
    op.create_index(
        op.f("idx_bet_archive_latest_version"),
        "bet_archive",
        ["match_id", "type", "period", sa.literal_column("version DESC")],
        unique=False,
    )
    op.drop_index(
        "idx_bet_latest_version", table_name="bet", postgresql_ops={"version": "desc"}
    )
    op.create_index(
        op.f("idx_bet_latest_version"),
        "bet",
        ["match_id", "type", "period", sa.literal_column("version DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
