"""bet key

Revision ID: e8895e7c6481
Revises: f65c039f2f07
Create Date: 2025-06-02 20:25:51.661772

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8895e7c6481"
down_revision: Union[str, None] = "f65c039f2f07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bet", sa.Column("key", sa.String(), nullable=False))
    op.drop_index("idx_bet_latest_version", table_name="bet")
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", "version"],
        unique=False,
        postgresql_ops={"version": "desc"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_bet_latest_version", table_name="bet", postgresql_ops={"version": "desc"}
    )
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", sa.text("version DESC")],
        unique=False,
    )
    op.drop_column("bet", "key")
    # ### end Alembic commands ###
