"""invite code email null

Revision ID: e8a27cfd106b
Revises: 8ae4942f68b3
Create Date: 2025-08-17 15:22:56.554308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a27cfd106b'
down_revision: Union[str, None] = '8ae4942f68b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_bet_latest_version'), table_name='bet')
    op.create_index('idx_bet_latest_version', 'bet', ['match_id', 'type', 'period', 'version'], unique=False, postgresql_ops={'version': 'desc'})
    op.alter_column('invite_code', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq_user_email_code'), 'invite_code', type_='unique')
    op.create_index(op.f('ix_invite_code_code'), 'invite_code', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invite_code_code'), table_name='invite_code')
    op.create_unique_constraint(op.f('uq_user_email_code'), 'invite_code', ['user_email', 'code'], postgresql_nulls_not_distinct=False)
    op.alter_column('invite_code', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('idx_bet_latest_version', table_name='bet', postgresql_ops={'version': 'desc'})
    op.create_index(op.f('idx_bet_latest_version'), 'bet', ['match_id', 'type', 'period', sa.literal_column('version DESC')], unique=False)
    # ### end Alembic commands ###
