"""point nullable

Revision ID: ed019910fece
Revises: 616867e78327
Create Date: 2025-04-06 21:06:03.183188

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed019910fece"
down_revision: Union[str, None] = "616867e78327"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bet", "point", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )

    op.drop_index("idx_bet_latest_version", table_name="bet")
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", "version"],
        unique=False,
        postgresql_ops={"version": "desc"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_bet_latest_version", table_name="bet", postgresql_ops={"version": "desc"}
    )
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", sa.text("version DESC")],
        unique=False,
    )
    op.alter_column(
        "bet", "point", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    # ### end Alembic commands ###
