"""double unique constraint to table league

Revision ID: ef61e6580d14
Revises: 270511669ddf
Create Date: 2025-01-22 20:07:18.977349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef61e6580d14"
down_revision: Union[str, None] = "270511669ddf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("league_name_key", "league", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("league_name_key", "league", ["name"])
    # ### end Alembic commands ###
