"""team table add

Revision ID: ef6e3d889bb8
Revises: 89c343baf15c
Create Date: 2025-03-11 21:41:44.574309

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ef6e3d889bb8"
down_revision: Union[str, None] = "89c343baf15c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["league_id"], ["league.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "league_id", name="uq_team_combination"),
    )
    op.create_index(op.f("ix_team_league_id"), "team", ["league_id"], unique=False)
    op.drop_index("idx_bet_latest_version", table_name="bet")
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", "version"],
        unique=False,
        postgresql_ops={"version": "desc"},
    )
    op.add_column("match_member", sa.Column("home_id", sa.Integer(), nullable=False))
    op.add_column("match_member", sa.Column("away_id", sa.Integer(), nullable=False))
    op.drop_index("ix_match_member_match_id_side", table_name="match_member")
    op.drop_constraint("uq_match_combination", "match_member", type_="unique")
    op.create_index(
        op.f("ix_match_member_away_id"), "match_member", ["away_id"], unique=False
    )
    op.create_index(
        op.f("ix_match_member_home_id"), "match_member", ["home_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_match_member_combination",
        "match_member",
        ["match_id", "home_id", "away_id"],
    )
    op.create_foreign_key(
        None, "match_member", "team", ["home_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "match_member", "team", ["away_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("match_member", "side")
    op.drop_column("match_member", "name")
    op.drop_column("match_member", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match_member",
        sa.Column(
            "status",
            postgresql.ENUM("win", "lose", name="matchresultenum"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "match_member",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "match_member",
        sa.Column(
            "side",
            postgresql.ENUM("home", "away", name="matchsideenum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "match_member", type_="foreignkey")
    op.drop_constraint(None, "match_member", type_="foreignkey")
    op.drop_constraint("uq_match_member_combination", "match_member", type_="unique")
    op.drop_index(op.f("ix_match_member_home_id"), table_name="match_member")
    op.drop_index(op.f("ix_match_member_away_id"), table_name="match_member")
    op.create_unique_constraint(
        "uq_match_combination", "match_member", ["match_id", "side"]
    )
    op.create_index(
        "ix_match_member_match_id_side",
        "match_member",
        ["match_id", "side"],
        unique=False,
    )
    op.drop_column("match_member", "away_id")
    op.drop_column("match_member", "home_id")
    op.drop_index(
        "idx_bet_latest_version", table_name="bet", postgresql_ops={"version": "desc"}
    )
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", sa.text("version DESC")],
        unique=False,
    )
    op.drop_index(op.f("ix_team_league_id"), table_name="team")
    op.drop_table("team")
    # ### end Alembic commands ###
