"""invite code

Revision ID: f175fa9536e8
Revises: e8895e7c6481
Create Date: 2025-08-16 22:59:49.562926

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "f175fa9536e8"
down_revision: Union[str, None] = "e8895e7c6481"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("user", sa.Column("email", sa.String(), nullable=False))

    op.create_unique_constraint(None, "user", ["email"])

    op.drop_constraint(op.f("user_uuid_key"), "user", type_="unique")
    op.drop_column("user", "uuid")

    op.create_table(
        "invite_code",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_email", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_email"], ["user.email"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_email", "code", name="uq_user_email_code"),
    )

    op.create_index(
        op.f("ix_invite_code_created_at"), "invite_code", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_invite_code_user_email"), "invite_code", ["user_email"], unique=False
    )

    op.drop_index(op.f("idx_bet_latest_version"), table_name="bet")
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", "version"],
        unique=False,
        postgresql_ops={"version": "desc"},
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "user", type_="unique")
    op.create_unique_constraint(
        op.f("user_uuid_key"), "user", ["uuid"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("user", "email")
    op.drop_index(
        "idx_bet_latest_version", table_name="bet", postgresql_ops={"version": "desc"}
    )
    op.create_index(
        op.f("idx_bet_latest_version"),
        "bet",
        ["match_id", "type", "period", sa.literal_column("version DESC")],
        unique=False,
    )
    op.drop_index(op.f("ix_invite_code_user_email"), table_name="invite_code")
    op.drop_index(op.f("ix_invite_code_created_at"), table_name="invite_code")
    op.drop_table("invite_code")
    # ### end Alembic commands ###
