"""parent id

Revision ID: f65c039f2f07
Revises: 4bbf805a1b1e
Create Date: 2025-05-20 21:00:15.544173

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f65c039f2f07"
down_revision: Union[str, None] = "4bbf805a1b1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_bet_latest_version", table_name="bet")
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", "version"],
        unique=False,
        postgresql_ops={"version": "desc"},
    )
    op.add_column("match", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_match_parent_id"), "match", ["parent_id"], unique=False)
    op.create_foreign_key(None, "match", "match", ["parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "match", type_="foreignkey")
    op.drop_index(op.f("ix_match_parent_id"), table_name="match")
    op.drop_column("match", "parent_id")
    op.drop_index(
        "idx_bet_latest_version", table_name="bet", postgresql_ops={"version": "desc"}
    )
    op.create_index(
        "idx_bet_latest_version",
        "bet",
        ["match_id", "type", "period", sa.text("version DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
